//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VapeStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flavor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flavor()
        {
            this.Characteristics = new HashSet<Characteristic>();
        }
    
        public string JuiceID { get; set; }
        public string Flavor1 { get; set; }
        public string FlavorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Characteristic> Characteristics { get; set; }
        public virtual Juice Juice { get; set; }
    }
}
